development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp:
    address: smtp.gmail.com
    port: 587
    user_name: <%= ENV["SMTP_USER_NAME"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
    authentication: plain
    enable_starttls_auto: true

  app:
    url: https://espressoapp.com.br/login

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp:
    address: <%= ENV["SMTP_ADDRESS"] %>
    port: <%= ENV["SMTP_PORT"] %>
    user_name: <%= ENV["SMTP_USER_NAME"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
    authentication: plain
    enable_starttls_auto: true

  app:
    url: <%= ENV["APP_URL"] %>
